apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-apps
spec:
  generators:
    - matrix:
        generators:
          # enriches applications per directory in clusters/base with cluster labels
          - clusters: {}
          # produces argocd app per directory in clusters/base
          - git:
              repoURL: &repo https://github.com/sreyardship/shipyard.git
              revision: main
              directories:
                - path: clusters/production/*
  template:
    metadata:
      name: "{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: *repo
        path: "{{path}}"
      destination:
        server: "{{server}}"
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
