apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd-ns.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/install.yaml
  - applicationset.yaml

patches:
  - path: argocd-cm.yaml

namespace: argocd
